# Libs

In [1]:
%pip install plotly
%pip install nbformat
%pip install statsmodels

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in c:\users\vlad\appdata\roaming\python\python313\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in c:\users\vlad\appdata\roaming\python\python313\site-packages (from plotly) (25.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbformat in c:\users\vlad\appdata\roaming\python\python313\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: pywin32>=300 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (310)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: statsmodels in c:\users\vlad\appdata\roaming\python\python313\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from statsmodels) (2.2.5)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from statsmodels) (1.15.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from statsmodels) (2.2.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vlad\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Load dataset
df = pd.read_csv("./data/final_player_dataset.csv")

# Preview
df.head()

,player_id_players_source,player_id_profiles_source,name,league,current_club_id,current_club_name,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
0,3333,791,James Milner,Premier League,1237,Brighton and Hove Albion Football Club,England,England,1986-01-04 00:00:00,Central Midfield,...,1.0195,0.623653,6.711111,8.0,2.0,2.0,0.0,14.0,6.0,0.0
1,7161,142390,Jonas Hofmann,Bundesliga,15,Bayer 04 Leverkusen Fußball,Germany,Germany,1992-07-14 00:00:00,Attacking Midfield,...,1.5770,1.770580,6.742857,21.0,7.0,3.0,0.0,13.0,2.0,0.0
2,11530,122922,Lionel Carole,Super Lig,3205,Kayserispor Kulübü,France,France,1991-04-12 00:00:00,Left-Back,...,NaN,0.529125,6.645000,0.0,0.0,4.0,0.0,27.0,23.0,0.0
3,12282,44864,Daley Blind,LaLiga,12321,Girona Fútbol Club S. A. D.,Netherlands,Netherlands,1990-03-09 00:00:00,Centre-Back,...,0.0937,1.059539,6.974074,3.0,1.0,1.0,0.0,48.0,36.0,0.0
4,15452,3041,Raúl Albiol,Serie A,4172,Pisa Sporting Club,Spain,Spain,1985-09-04 00:00:00,Centre-Back,...,0.0678,0.293735,6.675000,1.0,0.0,1.0,0.0,7.0,6.0,0.0

# Data Prep

In [3]:
print(df.shape)        # nr. linii + coloane
print(df.columns)      # coloane
df.info()              # tipuri de date
df.describe()          # statistici numerice

(3870, 31)
Index(['player_id_players_source', 'player_id_profiles_source', 'name',
       'league', 'current_club_id', 'current_club_name', 'country_of_birth',
       'country_of_citizenship', 'date_of_birth', 'sub_position', 'position',
       'foot', 'height_in_cm', 'current_national_team_id',
       'market_value_in_eur', 'market_value_profiles', 'appearances',
       'matches_started', 'minutes_played', 'goals', 'assists',
       'expected_goals', 'expected_assists', 'rating', 'total_shots',
       'shots_on_target', 'yellow_cards', 'red_cards', 'tackles',
       'interceptions', 'saves'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3870 entries, 0 to 3869
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   player_id_players_source   3870 non-null   int64
 1   player_id_profiles_source  3870 non-null   int64
 2   name                       3870 non-null   object
 3   league                     3870 non-null   object
 4   current_club_id            3870 non-null   int64
 5   current_club_name          3870 non-null   object
 6   country_of_birth           3789 non-null   object
 7   country_of_citizenship     3870 non-null   object
 8   date_of_birth              3870 non-null   object
 9   sub_position               3869 non-null   object
 10  position                   3870 non-null   object
 11  foot                       3829 non-null   object
 12  height_in_cm               3821 non-null   float64
 13  current_national_team_id   1063 non-null   float64
 14  market_value_in_eur        3824 non-null   float64
 15  market_value_profiles      3794 non-null   float64
 16  appearances                3484 non-null   float64
 17  matches_started            3484 non-null   float64
 18  minutes_played             3484 non-null   float64
 19  goals                      3484 non-null   float64
 20  assists                    3484 non-null   float64
 21  expected_goals             3000 non-null   float64
 22  expected_assists           3472 non-null   float64
 23  rating                     3484 non-null   float64
 24  total_shots                3484 non-null   float64
 25  shots_on_target            3484 non-null   float64
 26  yellow_cards               3484 non-null   float64
 27  red_cards                  3484 non-null   float64
 28  tackles                    3484 non-null   float64
 29  interceptions              3484 non-null   float64
 30  saves                      3484 non-null   float64
dtypes: float64(19), int64(3), object(9)
memory usage: 937.4+ KB

,player_id_players_source,player_id_profiles_source,current_club_id,height_in_cm,current_national_team_id,market_value_in_eur,market_value_profiles,appearances,matches_started,minutes_played,...,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
count,3.870000e+03,3.870000e+03,3870.000000,3821.000000,1063.000000,3.824000e+03,3.794000e+03,3484.000000,3484.000000,3484.000000,...,3000.000000,3472.000000,3484.000000,3484.000000,3484.000000,3484.000000,3484.000000,3484.000000,3484.000000,3484.000000
mean,5.536205e+05,9.267987e+05,2107.051680,183.652185,4371.804327,9.502232e+06,9.521650e+06,17.217853,12.489380,1122.641791,...,1.834383,1.107927,6.742914,14.232204,4.917623,2.185706,0.113375,17.953502,9.415614,3.512629
std,3.080302e+05,4.672774e+05,8664.922205,6.821370,5582.431855,1.608909e+07,1.633565e+07,8.239204,8.775154,743.026509,...,2.410339,1.346271,0.547519,15.895611,6.564710,2.057517,0.341509,16.419270,9.812778,15.251217
min,3.333000e+03,7.910000e+02,3.000000,163.000000,3262.000000,2.500000e+04,2.300000e+04,1.000000,0.000000,1.000000,...,0.003200,0.000001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.158925e+05,8.004125e+05,210.000000,179.000000,3379.000000,1.000000e+06,9.412500e+05,10.000000,5.000000,476.750000,...,0.363800,0.165545,6.606250,3.000000,0.000000,0.000000,0.000000,4.000000,1.000000,0.000000
50%,5.249310e+05,9.551405e+05,610.000000,184.000000,3439.000000,3.500000e+06,3.300000e+06,19.000000,12.000000,1050.000000,...,0.996750,0.655713,6.750806,9.000000,3.000000,2.000000,0.000000,14.000000,6.000000,0.000000
75%,7.451952e+05,1.133235e+06,1304.000000,189.000000,3533.000000,1.200000e+07,1.110000e+07,24.000000,20.000000,1738.250000,...,2.200350,1.527032,6.916667,20.000000,7.000000,3.000000,0.000000,27.000000,15.000000,0.000000
max,1.510255e+06,2.504430e+06,110302.000000,210.000000,53982.000000,2.000000e+08,2.180000e+08,31.000000,31.000000,2790.000000,...,24.383200,14.657572,9.700000,111.000000,61.000000,12.000000,3.000000,96.000000,63.000000,134.000000

In [4]:
missing = df.isnull().sum().sort_values(ascending=False)
missing = missing[missing > 0]

print(missing)

current_national_team_id    2807
expected_goals               870
expected_assists             398
yellow_cards                 386
shots_on_target              386
tackles                      386
interceptions                386
rating                       386
goals                        386
minutes_played               386
assists                      386
matches_started              386
appearances                  386
total_shots                  386
red_cards                    386
saves                        386
country_of_birth              81
market_value_profiles         76
height_in_cm                  49
market_value_in_eur           46
foot                          41
sub_position                   1
dtype: int64

In [5]:
cols = [
    'expected_goals', 'expected_assists', 'rating',
    'goals', 'assists', 'minutes_played'
]

missing_rows = df[df[cols].isnull().any(axis=1)]
print(missing_rows.shape)
missing_rows.head(100)

(870, 31)

,player_id_players_source,player_id_profiles_source,name,league,current_club_id,current_club_name,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
2,11530,122922,Lionel Carole,Super Lig,3205,Kayserispor Kulübü,France,France,1991-04-12 00:00:00,Left-Back,...,NaN,0.529125,6.645000,0.0,0.0,4.0,0.0,27.0,23.0,0.0
7,17259,8959,Manuel Neuer,Bundesliga,27,FC Bayern München,Germany,Germany,1986-03-27 00:00:00,Goalkeeper,...,NaN,0.028313,6.921053,0.0,0.0,0.0,0.0,0.0,0.0,26.0
8,18940,13906,Rémy Riou,Ligue 1,10004,Paris Football Club,France,France,1987-08-06 00:00:00,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,21327,41615,Ron-Robert Zieler,Bundesliga,3,1. Fußball-Club Köln,Germany,Germany,1989-02-12 00:00:00,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,24846,9668,Ricardo Batista,Liga Portugal,3268,Casa Pia Atlético Clube,Portugal,Angola,1986-11-19 00:00:00,Goalkeeper,...,NaN,0.002474,6.875000,0.0,0.0,0.0,0.0,0.0,0.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,135747,139272,Luca Lezzerini,Serie A,430,Associazione Calcio Fiorentina,Italy,Italy,1995-03-24 00:00:00,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,136111,98059,Nicola Leali,Serie A,252,Genoa Cricket and Football Club,Italy,Italy,1993-02-17 00:00:00,Goalkeeper,...,NaN,0.041471,6.895000,0.0,0.0,2.0,1.0,1.0,1.0,55.0
266,136401,101367,Daniel Bentley,Premier League,543,Wolverhampton Wanderers Football Club,England,England,1993-07-13 00:00:00,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,138285,107264,Mika,Liga Portugal,979,Moreirense Futebol Clube,Switzerland,Portugal,1991-03-08 00:00:00,Goalkeeper,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,142310,139310,Willy Boly,Premier League,703,Nottingham Forest Football Club,France,Cote d'Ivoire,1991-02-03 00:00:00,Centre-Back,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# numar jucatori cu appearances = 0
num_zero_appearances = (df['appearances'] == 0).sum()

print(num_zero_appearances)

0

In [7]:
# current_national_team_id
df['current_national_team_id'] = df['current_national_team_id'].fillna(0)

# stats
stats_cols = [
    'expected_goals', 'expected_assists', 'yellow_cards',
    'shots_on_target', 'tackles', 'interceptions', 'rating',
    'goals', 'minutes_played', 'assists', 'matches_started',
    'appearances', 'total_shots', 'red_cards', 'saves'
]

df[stats_cols] = df[stats_cols].fillna(0)

# market_value_profiles
df['market_value_profiles'] = df['market_value_profiles'].fillna(0)

In [8]:
df = df.dropna(subset=['market_value_in_eur'])

print("Remaining rows:", len(df))

Remaining rows: 3824

In [9]:
missing = df.isnull().sum().sort_values(ascending=False)
missing = missing[missing > 0]

print(missing)

country_of_birth    72
height_in_cm        37
foot                36
sub_position         1
dtype: int64

# Handling Missing Values

In [10]:
missing_country = df[df['country_of_birth'].isnull()]
print(missing_country.shape)
missing_country

(72, 31)

,player_id_players_source,player_id_profiles_source,name,league,current_club_id,current_club_name,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
1542,432694,913584,Joshua Kitolano,Eredivisie,468,Sparta Rotterdam,NaN,Norway,2001-08-03 00:00:00,Defensive Midfield,...,1.8436,2.257933,6.938462,23.0,9.0,3.0,0.0,40.0,15.0,0.0
1691,472873,858266,Logi Tomasson,Super Lig,152,Samsunspor,NaN,Iceland,2000-09-13 00:00:00,Left-Back,...,0.8625,2.633169,6.845833,17.0,5.0,4.0,0.0,31.0,17.0,0.0
1953,542452,1004550,Jonathan Fischer,Ligue 1,347,Football Club de Metz,NaN,Denmark,2001-11-09 00:00:00,Goalkeeper,...,0.0000,0.025689,6.976923,0.0,0.0,0.0,0.0,0.0,0.0,90.0
2043,565436,1000548,Alonzo Engwanda,Eredivisie,200,Football Club Utrecht,NaN,Belgium,2003-01-27 00:00:00,Defensive Midfield,...,0.1623,0.874562,6.917857,7.0,1.0,4.0,0.0,80.0,41.0,0.0
2048,566677,1064359,Nelson Abbey,Liga Portugal,2425,Rio Ave Futebol Clube,NaN,England,2003-08-28 00:00:00,Centre-Back,...,0.0807,0.348218,6.500000,3.0,0.0,4.0,0.0,28.0,20.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3784,1237907,1922996,Serigne Diop,Ligue 1,3911,Stade brestois 29,NaN,Senegal,2005-05-12 00:00:00,Centre-Forward,...,0.1321,0.045984,6.550000,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3789,1457367,2430541,Ali Diabaté,Super Lig,152,Samsunspor,NaN,Cote d'Ivoire,2006-12-05 00:00:00,Centre-Back,...,0.0950,0.263077,6.700000,2.0,1.0,0.0,0.0,3.0,3.0,0.0
3831,649490,978327,Konan N'Dri,Serie A,1005,Unione Sportiva Lecce,NaN,Cote d'Ivoire,2000-10-27 00:00:00,Right Winger,...,0.7104,0.415370,6.630000,14.0,5.0,2.0,0.0,8.0,0.0,0.0
3866,1146453,1957718,Givaro Renwarin,Eredivisie,1269,Prins Hendrik Ende Desespereert Nimmer Combina...,NaN,Netherlands,2008-02-19 00:00:00,Central Midfield,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3869,1261642,1806732,Deivison Souza Brito,Liga Portugal,982,Clube Desportivo Nacional,NaN,Brazil,2006-05-04 00:00:00,Central Midfield,...,0.0000,0.019508,5.700000,0.0,0.0,1.0,1.0,3.0,0.0,0.0

In [11]:
missing_height = df[df['height_in_cm'].isnull()]
print(missing_height.shape)
missing_height

(37, 31)

,player_id_players_source,player_id_profiles_source,name,league,current_club_id,current_club_name,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
2151,587297,1065542,Dion Vlak,Eredivisie,724,Football Club Volendam,Netherlands,Netherlands,2001-06-28 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2422,654902,1095406,Aurelio Oehlers,Eredivisie,724,Football Club Volendam,Netherlands,Netherlands,2004-02-05 00:00:00,Right Winger,...,1.6644,2.233054,6.766667,17.0,10.0,1.0,0.0,13.0,4.0,0.0
2629,707915,1120887,Erkam Kömur,Super Lig,1467,Göztepe Sportif Yatırımlar A.Ş.,Türkiye,Türkiye,2002-07-15 00:00:00,Right-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2955,849404,1129463,Furkan Gedik,Super Lig,120,Kocaelispor Kulübü,Türkiye,Türkiye,2002-07-12 00:00:00,Left Winger,...,0.0000,0.001448,6.466667,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3126,928359,1841361,Myron Mau-Asam,Eredivisie,724,Football Club Volendam,NaN,Netherlands,2004-04-01 00:00:00,Central Midfield,...,0.0000,0.000760,6.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3178,943592,2007289,Jelani Seedorf,Eredivisie,1434,Sportclub Telstar,Netherlands,Netherlands,2004-12-12 00:00:00,Centre-Forward,...,0.9391,0.168963,6.616667,5.0,3.0,1.0,0.0,4.0,0.0,0.0
3334,1014172,1928510,Yannick Gerritsen,Eredivisie,317,Football Club Twente,Netherlands,Netherlands,2006-02-14 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3337,1015619,1442017,Ahmed Abdullahi,Premier League,289,Sunderland Association Football Club,Nigeria,Nigeria,2004-06-19 00:00:00,Centre-Forward,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3368,1047257,1469007,Rio Cardines,Premier League,873,Crystal Palace Football Club,England,Trinidad and Tobago,2006-07-01 00:00:00,Left-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3369,1047261,1465401,Caleb Kporha,Premier League,873,Crystal Palace Football Club,NaN,England,2006-07-15 00:00:00,Right-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3376,1052803,2193004,Sam de Laat,Eredivisie,467,Nijmegen Eendracht Combinatie,Netherlands,Netherlands,2006-06-12 00:00:00,Central Midfield,...,0.0000,0.008251,6.600000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3385,1055233,1939251,Jesper Tielemans,Eredivisie,724,Football Club Volendam,NaN,Netherlands,2006-05-17 00:00:00,Centre-Forward,...,0.0899,0.003305,6.400000,1.0,1.0,0.0,0.0,0.0,0.0,0.0
3408,1064184,1648751,Ayoni Santos,Eredivisie,468,Sparta Rotterdam,Netherlands,Netherlands,2005-07-18 00:00:00,Attacking Midfield,...,1.8266,1.204229,6.700000,16.0,6.0,2.0,0.0,42.0,11.0,0.0
3461,1088035,1893851,Tijmen Holla,Eredivisie,798,Excelsior Rotterdam,NaN,Netherlands,2006-07-25 00:00:00,Goalkeeper,...,0.0000,0.023519,6.400000,0.0,0.0,0.0,0.0,0.0,0.0,3.0
3466,1091353,1897492,Telli Siwe,Ligue 1,290,Association de la Jeunesse auxerroise,France,France,2004-12-14 00:00:00,Centre-Back,...,0.0205,0.018174,6.433333,1.0,0.0,0.0,0.0,4.0,4.0,0.0
3478,1102425,1652148,Giannino Vianello,Eredivisie,468,Sparta Rotterdam,NaN,Netherlands,2007-06-10 00:00:00,Left-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3483,1104231,1469273,Rojendro Oudsten,Eredivisie,1434,Sportclub Telstar,NaN,Suriname,2007-11-12 00:00:00,Central Midfield,...,0.1917,0.009575,6.500000,2.0,1.0,1.0,0.0,4.0,0.0,0.0
3491,1111077,1957736,Jaygo van Ommeren,Eredivisie,200,Football Club Utrecht,Netherlands,Netherlands,2008-05-08 00:00:00,Defensive Midfield,...,0.0407,0.022731,6.750000,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3501,1116537,1819304,Kevyn Monteiro,Liga Portugal,979,Moreirense Futebol Clube,NaN,Brazil,2005-09-13 00:00:00,Centre-Back,...,0.0000,0.109991,6.740000,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3555,1172424,1977230,Elvis Van der Laan,Eredivisie,202,Football Club Groningen,Sweden,Sweden,2008-02-29 00:00:00,Centre-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3559,1175048,2216656,Robin van Cruijsen,Eredivisie,724,Football Club Volendam,Netherlands,Netherlands,2006-02-20 00:00:00,Attacking Midfield,...,2.0749,3.256880,6.860000,15.0,9.0,5.0,0.0,11.0,11.0,0.0
3585,1196804,1935932,Anass Bouziane,Eredivisie,724,Football Club Volendam,NaN,Netherlands,2006-12-22 00:00:00,Defensive Midfield,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3592,1209519,1632791,Victor Ntino-Emo Gidado,Super Lig,2832,Gaziantep Futbol Kulübü A.Ş.,NaN,Nigeria,2004-07-14 00:00:00,Attacking Midfield,...,0.0196,0.006931,6.475000,1.0,0.0,0.0,0.0,4.0,1.0,0.0
3608,1245251,2456624,Zakaria Kassary,Liga Portugal,2521,Futebol Clube de Alverca,NaN,Morocco,2006-01-25 00:00:00,Central Midfield,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3612,1261143,2161813,Ali Osman Kalın,Super Lig,2832,Gaziantep Futbol Kulübü A.Ş.,Türkiye,Türkiye,2008-03-23 00:00:00,Left Winger,...,0.0315,0.000438,6.900000,1.0,0.0,0.0,0.0,1.0,2.0,0.0
3634,1346738,2197941,Thomas Goos,Eredivisie,132,Nooit Opgeven Altijd Doorzetten Aangenaam Door...,Netherlands,Netherlands,2008-01-01 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3641,1409754,2197943,Pepijn Reulen,Eredivisie,132,Nooit Opgeven Altijd Doorzetten Aangenaam Door...,Netherlands,Netherlands,2008-06-01 00:00:00,Centre-Forward,...,0.3421,0.074259,6.510000,4.0,2.0,1.0,0.0,3.0,0.0,0.0
3646,1456741,2266455,Gilbert Mendy,Super Lig,7160,Eyüp Spor Kulübü,NaN,Senegal,2004-11-05 00:00:00,Centre-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3650,1476385,2186070,Sil Blokhuis,Eredivisie,1304,Heracles Almelo,Netherlands,Netherlands,2008-03-18 00:00:00,Right Winger,...,0.0000,0.182571,6.800000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3764,1011214,1397819,İzzet Furkan Malak,Super Lig,1467,Göztepe Sportif Yatırımlar A.Ş.,Türkiye,Türkiye,2005-01-14 00:00:00,Central Midfield,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3773,1088311,2180363,Yassir Rahmouni,Eredivisie,1435,Go Ahead Eagles,Netherlands,Netherlands,2006-06-13 00:00:00,Central Midfield,...,0.0780,0.349882,6.657895,3.0,0.0,2.0,0.0,19.0,2.0,0.0
3783,1223303,2031279,Hasan Yakub İlçin,Super Lig,589,Antalyaspor,Türkiye,Türkiye,2009-03-24 00:00:00,Central Midfield,...,0.0000,0.033009,6.650000,0.0,0.0,0.0,0.0,4.0,2.0,0.0
3786,1255744,1960315,Lushendry Edward Martes,Eredivisie,468,Sparta Rotterdam,Netherlands,Netherlands,2008-05-06 00:00:00,Right-Back,...,0.2273,0.655754,6.870000,5.0,2.0,4.0,0.0,24.0,6.0,0.0
3857,976840,1622183,Charles-Andre Raux Yao,Super Lig,7160,Eyüp Spor Kulübü,France,France,2001-11-15 00:00:00,Central Midfield,...,0.4453,0.027454,6.625000,5.0,2.0,1.0,0.0,1.0,2.0,0.0
3864,1076671,1533919,Ege Yildirim,Super Lig,1467,Göztepe Sportif Yatırımlar A.Ş.,Türkiye,Türkiye,2007-04-18 00:00:00,Centre-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3866,1146453,1957718,Givaro Renwarin,Eredivisie,1269,Prins Hendrik Ende Desespereert Nimmer Combina...,NaN,Netherlands,2008-02-19 00:00:00,Central Midfield,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3867,1162654,1895833,Noam Obougou Jacquet,Ligue 1,738,Le Havre Athletic Club,France,France,2006-03-15 00:00:00,Centre-Forward,...,0.1253,0.022392,6.820000,4.0,3.0,0.0,0.0,0.0,1.0,0.0

In [12]:
missing_foot = df[df['foot'].isnull()]
print(missing_foot.shape)
missing_foot

(36, 31)

,player_id_players_source,player_id_profiles_source,name,league,current_club_id,current_club_name,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
266,136401,101367,Daniel Bentley,Premier League,543,Wolverhampton Wanderers Football Club,England,England,1993-07-13 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1180,357628,1468090,Alfon González,LaLiga,1050,Villarreal Club de Fútbol S.A.D.,Spain,Spain,1999-05-04 00:00:00,Left Winger,...,0.6882,0.161773,6.571429,11.0,7.0,0.0,0.0,1.0,1.0,0.0
2172,593410,1050457,Yahya Kalley,Liga Portugal,2431,Club Football Estrela da Amadora,Sweden,The Gambia,2001-03-20 00:00:00,Left-Back,...,0.0000,0.001870,6.450000,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2352,635371,1066470,Daniel Deen,Eredivisie,1090,Alkmaar Zaanstreek,NaN,Netherlands,2003-02-13 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2527,675844,991039,Adam Carlén,Eredivisie,798,Excelsior Rotterdam,Sweden,Sweden,2000-06-27 00:00:00,Defensive Midfield,...,0.2928,0.251859,6.722222,8.0,1.0,3.0,0.0,34.0,9.0,0.0
2552,685484,2216257,Luka Duric,Bundesliga,533,Turn- und Sportgemeinschaft 1899 Hoffenheim Fu...,Germany,Bosnia-Herzegovina,2003-06-18 00:00:00,Central Midfield,...,0.0000,0.001438,6.700000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2686,724025,1170900,Matěj Šín,Eredivisie,1090,Alkmaar Zaanstreek,Czech Republic,Czech Republic,2004-06-02 00:00:00,Attacking Midfield,...,1.2481,0.861562,6.700000,8.0,3.0,1.0,0.0,8.0,5.0,0.0
2775,747243,1126966,Gyan de Regt,Eredivisie,798,Excelsior Rotterdam,Netherlands,Netherlands,2003-08-18 00:00:00,Left Winger,...,3.4474,6.140276,6.703571,30.0,11.0,3.0,0.0,20.0,10.0,0.0
2809,779752,1548838,Soufiane Hetli,Eredivisie,1434,Sportclub Telstar,NaN,Netherlands,2001-05-30 00:00:00,Centre-Forward,...,4.5985,1.090725,6.612000,45.0,11.0,2.0,0.0,21.0,6.0,0.0
3126,928359,1841361,Myron Mau-Asam,Eredivisie,724,Football Club Volendam,NaN,Netherlands,2004-04-01 00:00:00,Central Midfield,...,0.0000,0.000760,6.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3172,940095,1511723,Nordin Bukala,Eredivisie,724,Football Club Volendam,NaN,Netherlands,2005-09-18 00:00:00,Central Midfield,...,2.0199,0.653438,6.719048,10.0,4.0,4.0,0.0,55.0,28.0,0.0
3178,943592,2007289,Jelani Seedorf,Eredivisie,1434,Sportclub Telstar,Netherlands,Netherlands,2004-12-12 00:00:00,Centre-Forward,...,0.9391,0.168963,6.616667,5.0,3.0,1.0,0.0,4.0,0.0,0.0
3282,991487,1930811,Abdoul Ouattara,Ligue 1,667,Racing Club de Strasbourg Alsace,Cote d'Ivoire,Cote d'Ivoire,2005-10-22 00:00:00,Right Winger,...,2.1694,0.883269,6.673913,23.0,9.0,2.0,0.0,19.0,14.0,0.0
3334,1014172,1928510,Yannick Gerritsen,Eredivisie,317,Football Club Twente,Netherlands,Netherlands,2006-02-14 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3337,1015619,1442017,Ahmed Abdullahi,Premier League,289,Sunderland Association Football Club,Nigeria,Nigeria,2004-06-19 00:00:00,Centre-Forward,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3350,1029376,1855744,Ramazan Bayram,Eredivisie,385,Fortuna Sittardia Combinatie,Belgium,Belgium,2004-10-12 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3376,1052803,2193004,Sam de Laat,Eredivisie,467,Nijmegen Eendracht Combinatie,Netherlands,Netherlands,2006-06-12 00:00:00,Central Midfield,...,0.0000,0.008251,6.600000,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3385,1055233,1939251,Jesper Tielemans,Eredivisie,724,Football Club Volendam,NaN,Netherlands,2006-05-17 00:00:00,Centre-Forward,...,0.0899,0.003305,6.400000,1.0,1.0,0.0,0.0,0.0,0.0,0.0
3461,1088035,1893851,Tijmen Holla,Eredivisie,798,Excelsior Rotterdam,NaN,Netherlands,2006-07-25 00:00:00,Goalkeeper,...,0.0000,0.023519,6.400000,0.0,0.0,0.0,0.0,0.0,0.0,3.0
3483,1104231,1469273,Rojendro Oudsten,Eredivisie,1434,Sportclub Telstar,NaN,Suriname,2007-11-12 00:00:00,Central Midfield,...,0.1917,0.009575,6.500000,2.0,1.0,1.0,0.0,4.0,0.0,0.0
3518,1133977,1542758,Issa Traoré,Bundesliga,15,Bayer 04 Leverkusen Fußball,NaN,Mali,2007-11-14 00:00:00,Centre-Back,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3532,1148221,1513291,Niels Martens,Eredivisie,385,Fortuna Sittardia Combinatie,NaN,Netherlands,2004-05-07 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3534,1150105,2114948,Pharell Hensel,Bundesliga,82,Verein für Leibesübungen Wolfsburg,Germany,Germany,2007-06-08 00:00:00,Central Midfield,...,0.0240,0.033062,6.533333,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3559,1175048,2216656,Robin van Cruijsen,Eredivisie,724,Football Club Volendam,Netherlands,Netherlands,2006-02-20 00:00:00,Attacking Midfield,...,2.0749,3.256880,6.860000,15.0,9.0,5.0,0.0,11.0,11.0,0.0
3569,1184614,2056009,Ofosu Boakye,Eredivisie,1435,Go Ahead Eagles,NaN,Ghana,2007-07-10 00:00:00,Centre-Forward,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3585,1196804,1935932,Anass Bouziane,Eredivisie,724,Football Club Volendam,NaN,Netherlands,2006-12-22 00:00:00,Defensive Midfield,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3598,1227106,2111258,Elias Legendre Quiñonez,Ligue 1,273,Stade Rennais Football Club,Ecuador,Ecuador,2008-04-22 00:00:00,Right Winger,...,0.1461,0.334148,6.425000,1.0,0.0,0.0,0.0,2.0,1.0,0.0
3617,1280281,1888501,Abdoulie Ceesay,Bundesliga,35,Fußball-Club St. Pauli von 1910,The Gambia,The Gambia,2004-01-05 00:00:00,Centre-Forward,...,0.5061,0.110545,6.446154,4.0,1.0,2.0,0.0,1.0,0.0,0.0
3634,1346738,2197941,Thomas Goos,Eredivisie,132,Nooit Opgeven Altijd Doorzetten Aangenaam Door...,Netherlands,Netherlands,2008-01-01 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3653,1510255,2455955,Miguel Silva,Liga Portugal,979,Moreirense Futebol Clube,Portugal,Portugal,2007-12-17 00:00:00,Defensive Midfield,...,0.0000,0.005753,6.600000,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3698,527597,1133370,Simon Emil Spari,Bundesliga,35,Fußball-Club St. Pauli von 1910,NaN,Austria,2002-06-16 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3759,985806,1184541,Alexander Freeman,LaLiga,1050,Villarreal Club de Fútbol S.A.D.,United States,United States,2004-08-09 00:00:00,Right-Back,...,0.0000,0.009500,6.550000,0.0,0.0,0.0,0.0,2.0,1.0,0.0
3773,1088311,2180363,Yassir Rahmouni,Eredivisie,1435,Go Ahead Eagles,Netherlands,Netherlands,2006-06-13 00:00:00,Central Midfield,...,0.0780,0.349882,6.657895,3.0,0.0,2.0,0.0,19.0,2.0,0.0
3787,1355285,2026440,Arthur Rampineli Borghi,Serie A,276,Verona Hellas Football Club,Brazil,Brazil,2007-07-27 00:00:00,Goalkeeper,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3866,1146453,1957718,Givaro Renwarin,Eredivisie,1269,Prins Hendrik Ende Desespereert Nimmer Combina...,NaN,Netherlands,2008-02-19 00:00:00,Central Midfield,...,0.0000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3867,1162654,1895833,Noam Obougou Jacquet,Ligue 1,738,Le Havre Athletic Club,France,France,2006-03-15 00:00:00,Centre-Forward,...,0.1253,0.022392,6.820000,4.0,3.0,0.0,0.0,0.0,1.0,0.0

In [13]:
missing_sub_position = df[df['sub_position'].isnull()]
print(missing_sub_position.shape)
missing_sub_position

(1, 31)

,player_id_players_source,player_id_profiles_source,name,league,current_club_id,current_club_name,country_of_birth,country_of_citizenship,date_of_birth,sub_position,...,expected_goals,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves
1308,386552,804621,Lassana Coulibaly,Serie A,1005,Unione Sportiva Lecce,Mali,Mali,1996-04-10 00:00:00,NaN,...,2.0414,0.852781,6.772,20.0,7.0,3.0,0.0,38.0,6.0,0.0

In [14]:
df.loc[df['player_id_players_source'] == 386552, 'sub_position'] = 'Central Midfield'
df.loc[df['player_id_players_source'] == 386552, 'position'] = 'Midfield'

In [15]:
df['country_of_birth'] = df['country_of_birth'].fillna(df['country_of_citizenship'])

In [16]:
median_height = df['height_in_cm'].median()

df['height_in_cm'] = df['height_in_cm'].fillna(median_height)

print("Median height used:", median_height)

Median height used: 184.0

In [17]:
most_common_foot = df['foot'].mode()[0]

df['foot'] = df['foot'].fillna(most_common_foot)

print("Most common foot:", most_common_foot)

Most common foot: right

In [18]:
missing = df.isnull().sum().sort_values(ascending=False)
missing = missing[missing > 0]

print(missing)

Series([], dtype: int64)

# Handling outliers

In [19]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# opțional: scoate coloane care nu au sens
exclude = ['player_id_profiles_source', 'player_id_players_source', 'current_club_id', 'current_national_team_id',
            'market_value_profiles']
numeric_cols = [col for col in numeric_cols if col not in exclude]

print(numeric_cols)

['height_in_cm', 'market_value_in_eur', 'appearances', 'matches_started', 'minutes_played', 'goals', 'assists', 'expected_goals', 'expected_assists', 'rating', 'total_shots', 'shots_on_target', 'yellow_cards', 'red_cards', 'tackles', 'interceptions', 'saves']

In [20]:
for col in numeric_cols:
    fig = px.box(
        df,
        x=col,
        title=f"Boxplot - {col}",
        points="outliers"  # arată punctele outlier
    )
    
    fig.show()

# Normalize (log transform) market values

In [21]:
df['log_market_value'] = np.log1p(df['market_value_in_eur'])

In [22]:
fig = px.box(
        df,
        x='log_market_value',
        title=f"Boxplot - log_market_value",
        points="outliers"  # arată punctele outlier
    )
    
fig.show()

In [23]:
fig = px.histogram(
    df,
    x="market_value_in_eur",
    nbins=50,
    title="Distribuția Market Value (raw)",
)

fig.update_layout(
    xaxis_title="Market Value (€)",
    yaxis_title="Număr jucători"
)

fig.show()

In [24]:
fig = px.histogram(
    df,
    x="log_market_value",
    nbins=50,
    title="Distribuția Log Market Value",
)

fig.update_layout(
    xaxis_title="Log Market Value",
    yaxis_title="Număr jucători"
)

fig.show()

In [25]:
df.dtypes

player_id_players_source       int64
player_id_profiles_source      int64
name                          object
league                        object
current_club_id                int64
current_club_name             object
country_of_birth              object
country_of_citizenship        object
date_of_birth                 object
sub_position                  object
position                      object
foot                          object
height_in_cm                 float64
current_national_team_id     float64
market_value_in_eur          float64
market_value_profiles        float64
appearances                  float64
matches_started              float64
minutes_played               float64
goals                        float64
assists                      float64
expected_goals               float64
expected_assists             float64
rating                       float64
total_shots                  float64
shots_on_target              float64
yellow_cards                 float64
red_cards                    float64
tackles                      float64
interceptions                float64
saves                        float64
log_market_value             float64
dtype: object

In [26]:
df.describe()

,player_id_players_source,player_id_profiles_source,current_club_id,height_in_cm,current_national_team_id,market_value_in_eur,market_value_profiles,appearances,matches_started,minutes_played,...,expected_assists,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves,log_market_value
count,3.824000e+03,3.824000e+03,3824.000000,3824.000000,3824.000000,3.824000e+03,3.824000e+03,3824.000000,3824.000000,3824.000000,...,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000
mean,5.465416e+05,9.147799e+05,2111.057793,183.623431,1215.279289,9.502232e+06,9.446951e+06,15.680962,11.378138,1022.636768,...,1.005787,6.131602,12.961820,4.478818,1.991370,0.103295,16.353818,8.577144,3.200314,14.944348
std,3.025429e+05,4.553776e+05,8706.664447,6.780435,3534.693223,1.608909e+07,1.629310e+07,9.274870,9.100066,778.106163,...,1.322294,2.006439,15.706623,6.421140,2.060091,0.327563,16.486889,9.743013,14.591540,1.671251
min,3.333000e+03,7.910000e+02,3.000000,163.000000,0.000000,2.500000e+04,0.000000e+00,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.126671
25%,3.149050e+05,7.988312e+05,234.000000,179.000000,0.000000,1.000000e+06,9.250000e+05,7.000000,3.000000,310.750000,...,0.073640,6.562500,1.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,13.815512
50%,5.191095e+05,9.482555e+05,610.000000,184.000000,0.000000,3.500000e+06,3.200000e+06,18.000000,10.000000,930.500000,...,0.531786,6.723669,8.000000,2.000000,1.000000,0.000000,12.000000,5.000000,0.000000,15.068274
75%,7.387478e+05,1.129364e+06,1304.000000,188.000000,3300.000000,1.200000e+07,1.100000e+07,24.000000,19.000000,1674.250000,...,1.396589,6.900000,18.000000,6.000000,3.000000,0.000000,26.000000,14.000000,0.000000,16.300417
max,1.510255e+06,2.504430e+06,110302.000000,210.000000,53982.000000,2.000000e+08,2.180000e+08,31.000000,31.000000,2790.000000,...,14.657572,9.700000,111.000000,61.000000,12.000000,3.000000,96.000000,63.000000,134.000000,19.113828

# Distributions

In [27]:
position_color_map = {
    "Goalkeeper": "#7f7f7f",
    "Defender": "#1f77b4",
    "Midfield": "#c9b800",
    "Attack": "#d62728"
}

def plot_position_distribution(df):
    counts = df["position"].value_counts().reset_index()
    counts.columns = ["position", "count"]
    counts["percent"] = 100 * counts["count"] / counts["count"].sum()

    fig = px.bar(
        counts,
        x="position",
        y="count",
        color="position",
        color_discrete_map=position_color_map,
        title="Distribuția jucătorilor pe poziții",
        text="count",
        custom_data=["percent"]
    )

    fig.update_traces(
        texttemplate="%{y} (%{customdata[0]:.1f}%)",
        textposition="outside",
        hovertemplate=(
            "Position: %{x}<br>"
            "Players: %{y}<br>"
            "Percent: %{customdata[0]:.1f}%<extra></extra>"
        )
    )

    fig.update_layout(
        xaxis_title="Position",
        yaxis_title="Număr jucători",
        showlegend=False
    )

    fig.show()

plot_position_distribution(df)

In [28]:
sub_position_color_map = {
    "Goalkeeper": "#7f7f7f",

    "Centre-Back": "#1f77b4",
    "Right-Back": "#4fa3d9",
    "Left-Back": "#7dbce2",

    "Defensive Midfield": "#c9b800",
    "Central Midfield": "#e0cf00",
    "Attacking Midfield": "#f0e442",
    "Right Midfield": "#d8cc3a",
    "Left Midfield": "#f5e86e",

    "Centre-Forward": "#d62728",
    "Second Striker": "#e44d4d",
    "Left Winger": "#ff5a5f",
    "Right Winger": "#ff8a80"
}

def plot_sub_position_distribution(df):
    sub_position_order = [
        "Goalkeeper",

        "Centre-Back", "Right-Back", "Left-Back",

        "Defensive Midfield", "Central Midfield", "Attacking Midfield",
        "Right Midfield", "Left Midfield",

        "Centre-Forward", "Second Striker", "Left Winger", "Right Winger"
    ]

    counts = df["sub_position"].value_counts().reindex(sub_position_order, fill_value=0).reset_index()
    counts.columns = ["sub_position", "count"]
    counts["percent"] = 100 * counts["count"] / counts["count"].sum()

    fig = px.bar(
        counts,
        x="sub_position",
        y="count",
        color="sub_position",
        color_discrete_map=sub_position_color_map,
        category_orders={"sub_position": sub_position_order},
        title="Distribuția jucătorilor pe sub-poziții",
        text="count",
        custom_data=["percent"]
    )

    fig.update_traces(
        texttemplate="%{y} (%{customdata[0]:.1f}%)",
        textposition="outside",
        hovertemplate=(
            "Sub-position: %{x}<br>"
            "Players: %{y}<br>"
            "Percent: %{customdata[0]:.1f}%<extra></extra>"
        )
    )

    fig.update_layout(
        xaxis_title="Sub-position",
        yaxis_title="Număr jucători",
        xaxis_tickangle=-35,
        showlegend=False
    )

    fig.show()

plot_sub_position_distribution(df)

In [29]:
def plot_league_distribution_with_logos(df, logo_map, league_color_map=None):
    league_order = [
        "Premier League",
        "LaLiga",
        "Bundesliga",
        "Serie A",
        "Ligue 1",
        "Liga Portugal",
        "Eredivisie",
        "Super Lig"
    ]

    counts = df["league"].value_counts().reindex(league_order, fill_value=0).reset_index()
    counts.columns = ["league", "count"]
    counts["percent"] = 100 * counts["count"] / counts["count"].sum()

    fig = px.bar(
        counts,
        x="league",
        y="count",
        color="league",
        color_discrete_map=league_color_map,
        text="count",
        custom_data=["percent"],
        title="Distribuția jucătorilor pe ligi"
    )

    fig.update_traces(
        texttemplate="%{y} (%{customdata[0]:.1f}%)",
        textposition="outside",
        hovertemplate=(
            "League: %{x}<br>"
            "Players: %{y}<br>"
            "Percent: %{customdata[0]:.1f}%<extra></extra>"
        )
    )

    max_count = counts["count"].max()

    fig.update_yaxes(range=[0, 1.15 * max_count])

    fig.update_layout(
        xaxis_title="League",
        yaxis_title="Număr jucători",
        showlegend=False,
        xaxis_tickangle=-30
    )

    # logo-uri CENTRATE în bare
    for _, row in counts.iterrows():
        league = row["league"]
        count = row["count"]

        if league in logo_map and count > 0:
            fig.add_layout_image(
                dict(
                    source=logo_map[league],   # cale locală, URL sau PIL image
                    x=league,
                    y=count * 0.55,               # centru pe verticală
                    xref="x",
                    yref="y",
                    xanchor="center",
                    yanchor="middle",
                    sizex=0.7,                 # aproape cât bara
                    sizey=0.5 * count,         # ocupă ~60% din înălțimea barei
                    sizing="contain",
                    layer="above",
                    opacity=0.95
                )
            )

    fig.show()

In [30]:
logo_map = {
    "Premier League": "logos/premierleague.png",
    "LaLiga": "logos/laliga.png",
    "Bundesliga": "logos/bundesliga.png",
    "Serie A": "logos/seriea.png",
    "Ligue 1": "logos/ligue1.png",
    "Liga Portugal": "logos/ligaportugal.png",
    "Eredivisie": "logos/eredivisie.png",
    "Super Lig": "logos/superlig.png"
}

league_color_map = {
    "Premier League": "#3D195B",
    "LaLiga": "#1E1E1E",
    "Bundesliga": "#D20515",
    "Serie A": "#008FD7",
    "Ligue 1": "#091C3E",
    "Liga Portugal": "#006B3F",
    "Eredivisie": "#FF7A00",
    "Super Lig": "#FFFFFF"
}

plot_league_distribution_with_logos(df, logo_map, league_color_map=league_color_map)

In [31]:
fig = px.pie(
    df,
    names="foot",
    title="Distribuția piciorului dominant"
)

fig.update_traces(textinfo="label+percent+value")

fig.show()

In [32]:
fig = px.histogram(
    df,
    x="height_in_cm",
    nbins=30,
    title="Distribuția înălțimii jucătorilor",
)

fig.update_layout(
    xaxis_title="Înălțime (cm)",
    yaxis_title="Număr jucători"
)

fig.show()

In [33]:
import plotly.graph_objects as go

rare_sub_positions = ["Right Midfield", "Left Midfield", "Second Striker"]

rare_players = df[
    df["sub_position"].isin(rare_sub_positions)
][["name", "current_club_name", "sub_position"]].sort_values(
    by=["sub_position", "current_club_name", "name"]
)

fig = go.Figure(data=[go.Table(
    header=dict(
        values=["Name", "Current Club", "Sub-position"],
        align="left"
    ),
    cells=dict(
        values=[
            rare_players["name"],
            rare_players["current_club_name"],
            rare_players["sub_position"]
        ],
        align="left"
    )
)])

fig.update_layout(title="Players in Rare Sub-positions")
fig.show()

In [34]:
df["date_of_birth"] = pd.to_datetime(df["date_of_birth"], errors="coerce")

In [35]:
today = pd.Timestamp.today()

df["age_years_int"] = ((today - df["date_of_birth"]).dt.days // 365.25).astype("Int64")

In [36]:
age_bins = [0, 18, 21, 24, 27, 34, 41, 100]
age_labels = ["U18", "19-21", "22-24", "25-27", "28-34", "35-41", "42+"]

df["age_bucket"] = pd.cut(
    df["age_years_int"],
    bins=age_bins,
    labels=age_labels,
    right=True
)

In [37]:
fig = px.histogram(
    df,
    x="age_years_int",
    nbins=30,
    title="Distribuția vârstei jucătorilor",
)

fig.update_layout(
    xaxis_title="Vârstă (ani)",
    yaxis_title="Număr jucători"
)

fig.show()

In [38]:
age_order = ["U18", "19-21", "22-24", "25-27", "28-34", "35-41", "42+"]

counts = df["age_bucket"].value_counts().reindex(age_order, fill_value=0).reset_index()
counts.columns = ["age_bucket", "count"]
counts["percent"] = 100 * counts["count"] / counts["count"].sum()

fig = px.bar(
    counts,
    x="age_bucket",
    y="count",
    text="count",
    custom_data=["percent"],
    title="Distribuția pe grupe de vârstă",
    category_orders={"age_bucket": age_order}
)

fig.update_traces(
    texttemplate="%{y} (%{customdata[0]:.1f}%)",
    textposition="outside",
    hovertemplate=(
        "Age bucket: %{x}<br>"
        "Players: %{y}<br>"
        "Percent: %{customdata[0]:.1f}%<extra></extra>"
    )
)

fig.update_layout(
    xaxis_title="Grupă de vârstă",
    yaxis_title="Număr jucători"
)

fig.show()

In [60]:
country_counts = (
    df["country_of_citizenship"]
    .value_counts()
    .reset_index()
)

country_counts.columns = ["country", "count"]

fig = px.choropleth(
    country_counts,
    locations="country",
    locationmode="country names",  # 👈 important
    color="count",
    hover_name="country",
    color_continuous_scale="Blues",
    title="Distribuția jucătorilor pe naționalitate"
)

fig.show()

C:\Users\Vlad\AppData\Local\Temp\ipykernel_35968\2481465906.py:9: DeprecationWarning: The library used by the *country names* `locationmode` option is changing in an upcoming version. Country names in existing plots may not work in the new version. To ensure consistent behavior, consider setting `locationmode` to *ISO-3*.
  fig = px.choropleth(

In [39]:
df.describe()

,player_id_players_source,player_id_profiles_source,current_club_id,date_of_birth,height_in_cm,current_national_team_id,market_value_in_eur,market_value_profiles,appearances,matches_started,...,rating,total_shots,shots_on_target,yellow_cards,red_cards,tackles,interceptions,saves,log_market_value,age_years_int
count,3.824000e+03,3.824000e+03,3824.000000,3824,3824.000000,3824.000000,3.824000e+03,3.824000e+03,3824.000000,3824.000000,...,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.000000,3824.0
mean,5.465416e+05,9.147799e+05,2111.057793,1999-12-02 18:18:27.112970624,183.623431,1215.279289,9.502232e+06,9.446951e+06,15.680962,11.378138,...,6.131602,12.961820,4.478818,1.991370,0.103295,16.353818,8.577144,3.200314,14.944348,25.884676
min,3.333000e+03,7.910000e+02,3.000000,1983-07-28 00:00:00,163.000000,0.000000,2.500000e+04,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.126671,16.0
25%,3.149050e+05,7.988312e+05,234.000000,1996-12-27 12:00:00,179.000000,0.000000,1.000000e+06,9.250000e+05,7.000000,3.000000,...,6.562500,1.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,13.815512,22.0
50%,5.191095e+05,9.482555e+05,610.000000,2000-05-25 00:00:00,184.000000,0.000000,3.500000e+06,3.200000e+06,18.000000,10.000000,...,6.723669,8.000000,2.000000,1.000000,0.000000,12.000000,5.000000,0.000000,15.068274,25.0
75%,7.387478e+05,1.129364e+06,1304.000000,2003-05-14 06:00:00,188.000000,3300.000000,1.200000e+07,1.100000e+07,24.000000,19.000000,...,6.900000,18.000000,6.000000,3.000000,0.000000,26.000000,14.000000,0.000000,16.300417,29.0
max,1.510255e+06,2.504430e+06,110302.000000,2009-12-31 00:00:00,210.000000,53982.000000,2.000000e+08,2.180000e+08,31.000000,31.000000,...,9.700000,111.000000,61.000000,12.000000,3.000000,96.000000,63.000000,134.000000,19.113828,42.0
std,3.025429e+05,4.553776e+05,8706.664447,NaN,6.780435,3534.693223,1.608909e+07,1.629310e+07,9.274870,9.100066,...,2.006439,15.706623,6.421140,2.060091,0.327563,16.486889,9.743013,14.591540,1.671251,4.606519

In [58]:
df.dtypes

player_id_players_source              int64
player_id_profiles_source             int64
name                                 object
league                               object
current_club_id                       int64
current_club_name                    object
country_of_birth                     object
country_of_citizenship               object
date_of_birth                datetime64[ns]
sub_position                         object
position                             object
foot                                 object
height_in_cm                        float64
current_national_team_id            float64
market_value_in_eur                 float64
market_value_profiles               float64
appearances                         float64
matches_started                     float64
minutes_played                      float64
goals                               float64
assists                             float64
expected_goals                      float64
expected_assists                    float64
rating                              float64
total_shots                         float64
shots_on_target                     float64
yellow_cards                        float64
red_cards                           float64
tackles                             float64
interceptions                       float64
saves                               float64
log_market_value                    float64
age_years_int                         Int64
age_bucket                         category
dtype: object

# Scatter Plots

In [41]:
import plotly.express as px

def scatter_with_trend(df, x_col, title):
    fig = px.scatter(
        df,
        x=x_col,
        y="market_value_in_eur",   # ✅ raw
        trendline="ols",
        title=title,
        opacity=0.6
    )

    fig.update_layout(
        xaxis_title=x_col,
        yaxis_title="Market Value (€)"
    )

    # 🔥 log scale pe axa Y (IMPORTANT)
    fig.update_yaxes(type="log")

    fig.show()

In [53]:
base_features = [
    "height_in_cm",
    "appearances",
    "matches_started",
    "minutes_played",
    "rating",
    "yellow_cards",
    "red_cards",
    "age_years_int"
]

for col in base_features:
    scatter_with_trend(df, col, f"{col} vs Market Value")

In [54]:
attackers = df[df["position"] == "Attack"]

attack_features = [
    "goals",
    "expected_goals",
    "total_shots",
    "shots_on_target"
]

for col in attack_features:
    scatter_with_trend(attackers, col, f"Attackers: {col} vs Market Value")

In [55]:
midfielders = df[df["position"] == "Midfield"]

mid_features = [
    "assists",
    "expected_assists"
]

for col in mid_features:
    scatter_with_trend(midfielders, col, f"Midfielders: {col} vs Market Value")

In [56]:
defenders = df[df["position"] == "Defender"]

def_features = [
    "tackles",
    "interceptions"
]

for col in def_features:
    scatter_with_trend(defenders, col, f"Defenders: {col} vs Market Value")

In [57]:
gks = df[df["position"] == "Goalkeeper"]

gk_features = [
    "saves"
]

for col in gk_features:
    scatter_with_trend(gks, col, f"Goalkeepers: {col} vs Market Value")

# Encoding Club Names

In [67]:
club_value = df.groupby("current_club_name")["market_value_in_eur"].mean()

df["club_avg_value"] = df["current_club_name"].map(club_value)

df["club_avg_value_log"] = np.log1p(df["club_avg_value"])

In [72]:
id="loo_encoding"
club_sum = df.groupby("current_club_name")["market_value_in_eur"].transform("sum")
club_count = df.groupby("current_club_name")["market_value_in_eur"].transform("count")

df["club_avg_loo"] = (club_sum - df["market_value_in_eur"]) / (club_count - 1)

df["club_avg_loo_log"] = np.log1p(df["club_avg_loo"])

# Correlations

In [73]:
# 🔹 1. Selectează toate coloanele numerice
numeric_df = df.select_dtypes(include=["int64", "float64"]).copy()

# 🔹 2. Elimină manual coloanele irelevante
cols_to_drop = [
    "player_id_players_source",
    "player_id_profiles_source",
    "current_club_id",
    "current_national_team_id",
    "market_value_profiles",
    "log_market_value"
]

numeric_df = numeric_df.drop(columns=cols_to_drop, errors="ignore")

# 🔹 3. Calculează matricea de corelație
corr_matrix = numeric_df.corr()

# 🔹 4. Plot heatmap interactiv
fig = px.imshow(
    corr_matrix,
    text_auto=".2f",
    color_continuous_scale="RdBu_r",
    title="Correlation Matrix"
)

fig.update_layout(width=900, height=800)
fig.show()

# 🔥 5. Corelații cu target-ul (market value)
corr_target = corr_matrix["market_value_in_eur"].sort_values(ascending=False)

print("Correlation with market_value_in_eur:")
print(corr_target)

# 🔹 6. Elimină self-correlation
corr_target = corr_target.drop("market_value_in_eur")

# 🔹 7. Barplot pentru vizualizare
corr_df = corr_target.reset_index()
corr_df.columns = ["feature", "correlation"]

fig = px.bar(
    corr_df,
    x="feature",
    y="correlation",
    title="Correlation with Market Value",
    text="correlation"
)

fig.update_traces(texttemplate="%{y:.2f}", textposition="outside")
fig.update_layout(xaxis_tickangle=-45)

fig.show()

Correlation with market_value_in_eur:
market_value_in_eur    1.000000
club_avg_value         0.679872
club_avg_loo           0.647038
club_avg_value_log     0.568418
club_avg_loo_log       0.553539
total_shots            0.422721
shots_on_target        0.411395
expected_goals         0.397762
goals                  0.393978
expected_assists       0.387788
assists                0.369155
minutes_played         0.319433
appearances            0.318131
matches_started        0.316560
tackles                0.242275
rating                 0.196467
interceptions          0.177856
yellow_cards           0.161506
red_cards              0.028856
saves                 -0.020817
height_in_cm          -0.041055
age_years_int         -0.135353
Name: market_value_in_eur, dtype: float64

# Constants

In [62]:
threshold = 0.95
variance_threshold = 1e-3  # pentru numeric

# 🔹 separă coloanele
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
categorical_cols = df.select_dtypes(include=["object"]).columns

# ========================
# NUMERIC
# ========================

print("=== Low variance numeric columns ===")
low_variance_cols = []

for col in numeric_cols:
    var = df[col].var()
    if var < variance_threshold:
        low_variance_cols.append((col, var))

for col, var in low_variance_cols:
    print(f"{col}: variance={var}")

# ========================
# CATEGORICAL
# ========================

print("\n=== Near-constant categorical columns ===")
near_constant_cat = []

for col in categorical_cols:
    value_dist = df[col].value_counts(normalize=True, dropna=False)
    if len(value_dist) > 0:
        top_freq = value_dist.iloc[0]
        if top_freq > threshold:
            near_constant_cat.append((col, top_freq))

for col, freq in near_constant_cat:
    print(f"{col}: {freq:.2%} same value")

# ========================
# CONSTANT (general)
# ========================

constant_cols = [col for col in df.columns if df[col].nunique(dropna=False) == 1]

print("\n=== Constant columns ===")
print(constant_cols)

=== Low variance numeric columns ===

=== Near-constant categorical columns ===

=== Constant columns ===
[]

# Rare Categories

In [63]:
country_counts = df["country_of_citizenship"].value_counts()

country_counts

country_of_citizenship
Spain           380
Netherlands     326
France          317
Germany         260
Türkiye         204
               ...
Puerto Rico       1
Cyprus            1
Mauritania        1
Peru              1
Sierra Leone      1
Name: count, Length: 115, dtype: int64

In [64]:
threshold = 0.01  # 1%

country_freq = df["country_of_citizenship"].value_counts(normalize=True)

rare_countries = country_freq[country_freq < threshold].index

print("Rare countries:")
print(list(rare_countries))

Rare countries:
['Austria', 'Ghana', 'Uruguay', 'Japan', 'United States', 'Serbia', 'Mali', 'Colombia', 'Greece', 'Algeria', 'Cameroon', 'Czech Republic', 'Bosnia-Herzegovina', 'Scotland', 'Suriname', 'Ukraine', 'Ireland', 'Romania', 'Curacao', 'Iceland', 'DR Congo', 'Angola', 'Slovakia', 'Kosovo', 'Wales', 'Albania', 'Hungary', 'Cape Verde', 'Georgia', 'Canada', 'Guinea-Bissau', 'Korea, South', 'Tunisia', 'The Gambia', 'Paraguay', 'Australia', 'Indonesia', 'Russia', 'Chile', 'Mexico', 'Ecuador', 'Israel', 'Venezuela', 'Finland', 'Burkina Faso', 'Slovenia', 'Guinea', 'Montenegro', 'Mozambique', 'Luxembourg', 'Haiti', 'Egypt', 'Togo', 'Gabon', 'Comoros', 'Jamaica', 'Northern Ireland', 'Uzbekistan', 'Benin', 'Bulgaria', 'North Macedonia', 'Honduras', 'Libya', 'Costa Rica', 'Dominican Republic', 'Congo', 'Lithuania', 'Central African Republic', 'New Zealand', 'Estonia', 'Guadeloupe', 'Tanzania', 'Zambia', 'Trinidad and Tobago', 'South Africa', 'Azerbaijan', 'Zimbabwe', 'Armenia', 'Iran', 'Syria', 'Equatorial Guinea', 'French Guiana', 'Faroe Islands', 'Panama', 'Jordan', 'Malaysia', 'Burundi', 'Saudi Arabia', 'Chad', 'Puerto Rico', 'Cyprus', 'Mauritania', 'Peru', 'Sierra Leone']

In [65]:
df["country_grouped"] = df["country_of_citizenship"].replace(
    rare_countries, "Other"
)

In [66]:
df["country_grouped"].value_counts()

country_grouped
Other            899
Spain            380
Netherlands      326
France           317
Germany          260
Türkiye          204
Portugal         191
England          189
Italy            189
Brazil           185
Argentina         84
Belgium           81
Morocco           67
Denmark           66
Cote d'Ivoire     58
Senegal           53
Sweden            52
Switzerland       47
Norway            47
Croatia           44
Nigeria           44
Poland            41
Name: count, dtype: int64

In [76]:
df.dtypes

player_id_players_source              int64
player_id_profiles_source             int64
name                                 object
league                               object
current_club_id                       int64
current_club_name                    object
country_of_birth                     object
country_of_citizenship               object
date_of_birth                datetime64[ns]
sub_position                         object
position                             object
foot                                 object
height_in_cm                        float64
current_national_team_id            float64
market_value_in_eur                 float64
market_value_profiles               float64
appearances                         float64
matches_started                     float64
minutes_played                      float64
goals                               float64
assists                             float64
expected_goals                      float64
expected_assists                    float64
rating                              float64
total_shots                         float64
shots_on_target                     float64
yellow_cards                        float64
red_cards                           float64
tackles                             float64
interceptions                       float64
saves                               float64
log_market_value                    float64
age_years_int                         Int64
age_bucket                         category
country_grouped                      object
club_avg_value                      float64
club_avg_value_log                  float64
club_avg_loo                        float64
club_avg_loo_log                    float64
dtype: object

# One Hot Encoding

In [78]:
categorical_cols = [
    "country_grouped",
    "league",
    "sub_position",
    "foot"
]

df_encoded = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True
)

print("Original shape:", df.shape)
print("Encoded shape:", df_encoded.shape)

Original shape: (3824, 39)
Encoded shape: (3824, 77)

# Write Final Dataset

In [79]:
df_encoded.to_csv("./data/final_dataset_processed.csv", index=False)

## Dataset Features Overview

### 🔑 Primary Key
- `name`

---

### 🎯 Target
- `log_market_value`

---

### 📊 Features

#### 🧍 Demographics
- `age_years_int`
- `height_in_cm`

---

#### ⚽ Performance Stats (General)
- `minutes_played`
- `rating`
- `total_shots`
- `expected_assists`
- `yellow_cards`
- `red_cards`
- `tackles`
- `interceptions`
- `saves`

---

#### 🧠 Encoded Categorical Features (One-Hot)
- `league_*`
- `sub_position_*`
- `country_grouped_*`
- `foot_*`

---

#### ⚙️ Encoded Categorical Features (Leave One Out)
- `club_avg_loo_log`

---

### ❌ Dropped Features

#### 🔗 IDs / Technical
- `player_id_players_source` (used for merging)
- `player_id_profiles_source` (used for merging)

---

#### 🏟️ Club-related (redundant / encoded / leakage)
- `current_club_id` (redundant)
- `current_club_name` (encoded)
- `club_avg_value` (leakage)
- `club_avg_value_log` (leakage)
- `club_avg_loo` (alternative encoding, not used)

---

#### 🌍 Country-related
- `country_of_birth` (redundant)
- `country_of_citizenship` (transformed into `country_grouped`)
- `country_grouped` (encoded)

---

#### 📅 Time-related
- `date_of_birth` (used to compute age)
- `age_bucket` (redundant with numeric age)

---

#### ⚽ Position-related
- `position` (redundant with `sub_position`)
- `sub_position` (encoded)

---

#### 🦶 Other categorical
- `foot` (encoded)
- `league` (encoded)

---

#### 🏆 Misc
- `current_national_team_id` (redundant)
- `market_value_profiles` (redundant)
- `market_value_in_eur` → transformed into `log_market_value` (to reduce skewness)

---

#### 📉 Highly Correlated / Removed for Redundancy
- `appearances` (correlated with `minutes_played`)
- `matches_started` (correlated with `minutes_played`)
- `goals` (correlated with `total_shots`)
- `expected_goals` (correlated with `total_shots`)
- `shots_on_target` (correlated with `total_shots`)
- `assists` (correlated with `expected_assists`)